name: project
description: "Gestionar tus finanzas!!"
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  sqflite: ^2.2.0
  path: ^1.8.3
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/expense_types.json